//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.30 at 11:36:03 AM CEST 
//


package gov.nist.scap.schema.cvss_v2._0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for confidenceEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="confidenceEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="UNCONFIRMED"/>
 *     &lt;enumeration value="UNCORROBORATED"/>
 *     &lt;enumeration value="CONFIRMED"/>
 *     &lt;enumeration value="NOT_DEFINED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "confidenceEnumType")
@XmlEnum
public enum ConfidenceEnumType {

    UNCONFIRMED,
    UNCORROBORATED,
    CONFIRMED,
    NOT_DEFINED;

    public String value() {
        return name();
    }

    public static ConfidenceEnumType fromValue(String v) {
        return valueOf(v);
    }

}
