//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.30 at 11:36:03 AM CEST 
//


package gov.nist.scap.schema.cvss_v2._0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for environmentalMetricsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="environmentalMetricsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://scap.nist.gov/schema/cvss-v2/0.2}metricsType">
 *       &lt;sequence>
 *         &lt;element name="score" type="{http://scap.nist.gov/schema/cvss-v2/0.2}zeroToTenDecimalType" minOccurs="0"/>
 *         &lt;group ref="{http://scap.nist.gov/schema/cvss-v2/0.2}environmentalVectorsGroup"/>
 *         &lt;element name="source" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="generated-on-datetime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "environmentalMetricsType", propOrder = {
    "score",
    "collateralDamagePotential",
    "targetDistribution",
    "confidentialityRequirement",
    "integrityRequirement",
    "availabilityRequirement",
    "source",
    "generatedOnDatetime"
})
public class EnvironmentalMetricsType
    extends MetricsType
{

    protected BigDecimal score;
    @XmlElement(name = "collateral-damage-potential")
    protected CollateralDamagePotentialType collateralDamagePotential;
    @XmlElement(name = "target-distribution")
    protected TargetDistributionType targetDistribution;
    @XmlElement(name = "confidentiality-requirement")
    protected CiaRequirementType confidentialityRequirement;
    @XmlElement(name = "integrity-requirement")
    protected CiaRequirementType integrityRequirement;
    @XmlElement(name = "availability-requirement")
    protected CiaRequirementType availabilityRequirement;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String source;
    @XmlElement(name = "generated-on-datetime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar generatedOnDatetime;

    /**
     * Gets the value of the score property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setScore(BigDecimal value) {
        this.score = value;
    }

    /**
     * Gets the value of the collateralDamagePotential property.
     * 
     * @return
     *     possible object is
     *     {@link CollateralDamagePotentialType }
     *     
     */
    public CollateralDamagePotentialType getCollateralDamagePotential() {
        return collateralDamagePotential;
    }

    /**
     * Sets the value of the collateralDamagePotential property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollateralDamagePotentialType }
     *     
     */
    public void setCollateralDamagePotential(CollateralDamagePotentialType value) {
        this.collateralDamagePotential = value;
    }

    /**
     * Gets the value of the targetDistribution property.
     * 
     * @return
     *     possible object is
     *     {@link TargetDistributionType }
     *     
     */
    public TargetDistributionType getTargetDistribution() {
        return targetDistribution;
    }

    /**
     * Sets the value of the targetDistribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetDistributionType }
     *     
     */
    public void setTargetDistribution(TargetDistributionType value) {
        this.targetDistribution = value;
    }

    /**
     * Gets the value of the confidentialityRequirement property.
     * 
     * @return
     *     possible object is
     *     {@link CiaRequirementType }
     *     
     */
    public CiaRequirementType getConfidentialityRequirement() {
        return confidentialityRequirement;
    }

    /**
     * Sets the value of the confidentialityRequirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link CiaRequirementType }
     *     
     */
    public void setConfidentialityRequirement(CiaRequirementType value) {
        this.confidentialityRequirement = value;
    }

    /**
     * Gets the value of the integrityRequirement property.
     * 
     * @return
     *     possible object is
     *     {@link CiaRequirementType }
     *     
     */
    public CiaRequirementType getIntegrityRequirement() {
        return integrityRequirement;
    }

    /**
     * Sets the value of the integrityRequirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link CiaRequirementType }
     *     
     */
    public void setIntegrityRequirement(CiaRequirementType value) {
        this.integrityRequirement = value;
    }

    /**
     * Gets the value of the availabilityRequirement property.
     * 
     * @return
     *     possible object is
     *     {@link CiaRequirementType }
     *     
     */
    public CiaRequirementType getAvailabilityRequirement() {
        return availabilityRequirement;
    }

    /**
     * Sets the value of the availabilityRequirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link CiaRequirementType }
     *     
     */
    public void setAvailabilityRequirement(CiaRequirementType value) {
        this.availabilityRequirement = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the generatedOnDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGeneratedOnDatetime() {
        return generatedOnDatetime;
    }

    /**
     * Sets the value of the generatedOnDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGeneratedOnDatetime(XMLGregorianCalendar value) {
        this.generatedOnDatetime = value;
    }

}
