//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.30 at 11:36:03 AM CEST 
//


package gov.nist.scap.schema.cvss_v2._0;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nist.scap.schema.cvss_v2._0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nist.scap.schema.cvss_v2._0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CvssType }
     * 
     */
    public CvssType createCvssType() {
        return new CvssType();
    }

    /**
     * Create an instance of {@link CiaRequirementType }
     * 
     */
    public CiaRequirementType createCiaRequirementType() {
        return new CiaRequirementType();
    }

    /**
     * Create an instance of {@link TemporalMetricsType }
     * 
     */
    public TemporalMetricsType createTemporalMetricsType() {
        return new TemporalMetricsType();
    }

    /**
     * Create an instance of {@link CvssImpactType }
     * 
     */
    public CvssImpactType createCvssImpactType() {
        return new CvssImpactType();
    }

    /**
     * Create an instance of {@link CollateralDamagePotentialType }
     * 
     */
    public CollateralDamagePotentialType createCollateralDamagePotentialType() {
        return new CollateralDamagePotentialType();
    }

    /**
     * Create an instance of {@link TargetDistributionType }
     * 
     */
    public TargetDistributionType createTargetDistributionType() {
        return new TargetDistributionType();
    }

    /**
     * Create an instance of {@link AccessComplexityType }
     * 
     */
    public AccessComplexityType createAccessComplexityType() {
        return new AccessComplexityType();
    }

    /**
     * Create an instance of {@link CiaType }
     * 
     */
    public CiaType createCiaType() {
        return new CiaType();
    }

    /**
     * Create an instance of {@link RemediationLevelType }
     * 
     */
    public RemediationLevelType createRemediationLevelType() {
        return new RemediationLevelType();
    }

    /**
     * Create an instance of {@link ExploitabilityType }
     * 
     */
    public ExploitabilityType createExploitabilityType() {
        return new ExploitabilityType();
    }

    /**
     * Create an instance of {@link AccessVectorType }
     * 
     */
    public AccessVectorType createAccessVectorType() {
        return new AccessVectorType();
    }

    /**
     * Create an instance of {@link ConfidenceType }
     * 
     */
    public ConfidenceType createConfidenceType() {
        return new ConfidenceType();
    }

    /**
     * Create an instance of {@link BaseMetricsType }
     * 
     */
    public BaseMetricsType createBaseMetricsType() {
        return new BaseMetricsType();
    }

    /**
     * Create an instance of {@link EnvironmentalMetricsType }
     * 
     */
    public EnvironmentalMetricsType createEnvironmentalMetricsType() {
        return new EnvironmentalMetricsType();
    }

    /**
     * Create an instance of {@link AuthenticationType }
     * 
     */
    public AuthenticationType createAuthenticationType() {
        return new AuthenticationType();
    }

}
