//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.30 at 11:36:03 AM CEST 
//


package gov.nist.scap.schema.cvss_v2._0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for temporalMetricsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="temporalMetricsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://scap.nist.gov/schema/cvss-v2/0.2}metricsType">
 *       &lt;sequence>
 *         &lt;element name="score" type="{http://scap.nist.gov/schema/cvss-v2/0.2}zeroToTenDecimalType" minOccurs="0"/>
 *         &lt;element name="temporal-multiplier" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;group ref="{http://scap.nist.gov/schema/cvss-v2/0.2}temporalVectorsGroup"/>
 *         &lt;element name="source" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="generated-on-datetime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "temporalMetricsType", propOrder = {
    "score",
    "temporalMultiplier",
    "exploitability",
    "remediationLevel",
    "reportConfidence",
    "source",
    "generatedOnDatetime"
})
public class TemporalMetricsType
    extends MetricsType
{

    protected BigDecimal score;
    @XmlElement(name = "temporal-multiplier")
    protected BigDecimal temporalMultiplier;
    protected ExploitabilityType exploitability;
    @XmlElement(name = "remediation-level")
    protected RemediationLevelType remediationLevel;
    @XmlElement(name = "report-confidence")
    protected ConfidenceType reportConfidence;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String source;
    @XmlElement(name = "generated-on-datetime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar generatedOnDatetime;

    /**
     * Gets the value of the score property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setScore(BigDecimal value) {
        this.score = value;
    }

    /**
     * Gets the value of the temporalMultiplier property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTemporalMultiplier() {
        return temporalMultiplier;
    }

    /**
     * Sets the value of the temporalMultiplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTemporalMultiplier(BigDecimal value) {
        this.temporalMultiplier = value;
    }

    /**
     * Gets the value of the exploitability property.
     * 
     * @return
     *     possible object is
     *     {@link ExploitabilityType }
     *     
     */
    public ExploitabilityType getExploitability() {
        return exploitability;
    }

    /**
     * Sets the value of the exploitability property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExploitabilityType }
     *     
     */
    public void setExploitability(ExploitabilityType value) {
        this.exploitability = value;
    }

    /**
     * Gets the value of the remediationLevel property.
     * 
     * @return
     *     possible object is
     *     {@link RemediationLevelType }
     *     
     */
    public RemediationLevelType getRemediationLevel() {
        return remediationLevel;
    }

    /**
     * Sets the value of the remediationLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemediationLevelType }
     *     
     */
    public void setRemediationLevel(RemediationLevelType value) {
        this.remediationLevel = value;
    }

    /**
     * Gets the value of the reportConfidence property.
     * 
     * @return
     *     possible object is
     *     {@link ConfidenceType }
     *     
     */
    public ConfidenceType getReportConfidence() {
        return reportConfidence;
    }

    /**
     * Sets the value of the reportConfidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfidenceType }
     *     
     */
    public void setReportConfidence(ConfidenceType value) {
        this.reportConfidence = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the generatedOnDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGeneratedOnDatetime() {
        return generatedOnDatetime;
    }

    /**
     * Sets the value of the generatedOnDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGeneratedOnDatetime(XMLGregorianCalendar value) {
        this.generatedOnDatetime = value;
    }

}
